create table if not exists public.user_workspaces (
  user_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.user_workspaces enable row level security;

create policy "user_workspaces_select_own"
on public.user_workspaces
for select
to authenticated
using (auth.uid()::text = user_id);

create policy "user_workspaces_insert_own"
on public.user_workspaces
for insert
to authenticated
with check (auth.uid()::text = user_id);

create policy "user_workspaces_update_own"
on public.user_workspaces
for update
to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

create table if not exists public.qa_reports (
  id bigint generated by default as identity primary key,
  author_id text not null,
  text_preview text not null default '',
  issue_count integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists qa_reports_author_id_created_at_idx
  on public.qa_reports (author_id, created_at desc);

alter table public.qa_reports enable row level security;

create policy "qa_reports_select_own"
on public.qa_reports
for select
to authenticated
using (auth.uid()::text = author_id);

create policy "qa_reports_insert_own"
on public.qa_reports
for insert
to authenticated
with check (auth.uid()::text = author_id);
